[[redirects]]
  from = "/about"
  to = "/src/pages/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/src/pages/contact.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/src/pages/projects.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200